<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>FirebaseWorkout</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>ComputerIssueReporter</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.FirebaseWorkout</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiFont Include="Fonts\OpenSans-Semibold.ttf" />
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Fonts\MaterialIcons-Regular.ttf" />
	  <None Remove="Fonts\OpenSans-Regular.ttf" />
	  <None Remove="Fonts\OpenSans-Semibold.ttf" />
	</ItemGroup>

	<ItemGroup>
	  <MauiFont Include="Fonts\MaterialIcons-Regular.ttf" />
	  <MauiFont Include="Fonts\OpenSans-Regular.ttf" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Service\DBService\Firebase\FirebaseRealtimeService2.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="BarcodeScanning.Native.Maui" Version="1.5.13" />
		<PackageReference Include="FirebaseAuthentication.net" Version="4.1.0" />
		<PackageReference Include="FirebaseDatabase.net" Version="5.0.0" />
		<PackageReference Include="FirebaseStorage.net" Version="1.0.3" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.5" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Views\AccountView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\AdminView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MainPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SignInView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SignUpView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\UsersListView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
